services:
  tickets-db:
    image: postgres:16
    container_name: tickets-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${TICKETS_DB_PASSWORD}
      POSTGRES_DB: ticketsdb
    ports:
      - "5432:5432"
    volumes:
      - tickets-pgdata:/var/lib/postgresql/data
    networks:
      - network

  notifications-db:
    image: postgres:16
    container_name: notifications-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${NOTIFICATIONS_DB_PASSWORD}
      POSTGRES_DB: notificationsdb
    ports:
      - "5433:5432"
    volumes:
      - notifications-pgdata:/var/lib/postgresql/data
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - network
  
  tickets-api:
    build:
      context: ./Tickets.Api
      dockerfile: Dockerfile
    container_name: tickets-api
    ports:
      - "5112:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=tickets-db;Port=5432;Database=ticketsDB;Username=postgres;Password=${TICKETS_DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - tickets-db
      - rabbitmq
    networks:
      - network

  notifications-api:
    build:
      context: ./Notifications.Api
      dockerfile: Dockerfile
    container_name: notifications-api
    ports:
      - "5201:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=notifications-db;Port=5432;Database=notificationsDB;Username=postgres;Password=${NOTIFICATIONS_DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - notifications-db
      - rabbitmq
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  tickets-pgdata:
  notifications-pgdata: